 export const dila = [
    {
        dilo:"Médea pomáhá Iásonovi získat zlaté rouno a zradí svého otce. S Iásonem i jejich dvěma syny prchá do Korintu. Korintský král Kreon však žádá Iásona, aby si vzal jeho dceru za manželku. Iáson souhlasí.Médeia se to dozví a je velmi rozzlobená. Plánuje pomstu Iásonovi, Kreonovi i jeho dceři. Médeia po svých dětech posílá dar nové manželce Iásonově- ozdobu do vlasů a šaty napuštěné jedem. Když si Iásonova manželka oblékne šaty a nasadí šperky, tak uhoří a spolu s ní i její otec Kreon, který se jí snaží pomoci. To ale Médei nestačí, chce Iásonovi ublížit ještě víc. Tak vlastníma rukama zabije i jejich dva syny.Nakonec Médea odjíždí i s těly obou synu k athénskému králi Aigeovi.",
        autor:"Euripidés, starořecký dramatik, pocházel ze Salamíny a byl jedním z největších tragických básníků starověkého Řecka. Narodil se kolem roku 480 př. n. l. a zemřel v roce 406 př. n. l. Byl známý pro své inovativní přístupy k dramatu, často zpochybňující tradiční morální hodnoty a zobrazující hluboké psychologické rozpory svých postav. Jeho hry, jako Médéia nebo Trojské ženy, zkoumají temnější stránky lidské psychiky a společenské otázky, jako jsou genderové role a mocenské vztahy. Byl mistrem dialogu a charakterizace, což jeho díla činí stále aktuálními."
    },
    {
        dilo:"Romeo a Julie, tragédie Williama Shakespeara, popisuje lásku dvou mladých z Verony, kteří pocházejí z nepřátelských rodin Monteků a Kapuletů. Romeo se zamiluje do Julie na bálu u Kapuletů. Přes vědomí nemožnosti vztahu se tajně vezmou. Následné konflikty vedou k smrti Romeova přítele Mercutia a Julieina bratrance Tybalta. Tragédie vrcholí sebevraždami Romea a Julie, které nakonec vedou k usmíření obou rodin. Dílo zkoumá téma zakázané lásky, mocenských bojů a tragických důsledků rodinné vendety, přičemž končí smířením rodin po smrti milenců.",
        autor:"William Shakespeare, narozený 23. dubna 1564 ve Stratfordu nad Avonou, je považován za jednoho z největších dramatiků. Jeho dílo zahrnuje 39 her a 154 sonetů, které zkoumají hluboké lidské emoce a etická dilemata. Mezi jeho nejznámější hry patří Hamlet, Othello, Král Lear a Macbeth. Tyto práce jsou ceněny pro jazykovou obratnost a psychologickou hloubku postav, reflektují společenské a politické napětí jeho doby a zároveň se dotýkají univerzálních témat jako láska, moc, zrada a pomsta. Shakespeare zemřel 23. dubna 1616, ale jeho vliv na světovou literaturu přetrvává."
    },
    {
        dilo:"Lakomec, komedie napsaná Molièrem, vypráví o Harpagonovi, extrémně lakomém a bohatém starci, který svou posedlostí penězi ovlivňuje životy svých dětí a okolí. Harpagon plánuje oženit se s mladou dívkou jménem Mariana, zatímco zároveň chce provdat svou dceru Élise za bohatého starce a oženit syna Cléanta s bohatou vdovou. Nečekaně se ale Cléante a Mariana zamilují. Situace se zamotává, když Harpagon obviní svou domácnost z krádeže svého drahocenného pokladu – hrsti zlaťáků ukrytých v zahradě. Komedie kulminuje řadou omylů a překvapení, které vede k odhalení pravých vztahů a Harpagonově ponaučení o důležitosti rodiny nad bohatstvím.",
        autor:"Molière, vlastním jménem Jean-Baptiste Poquelin, se narodil 15. ledna 1622 v Paříži a zemřel 17. února 1673. Byl francouzský dramatik, herec a režisér, považovaný za jednoho z největších komediálních dramatiků všech dob. Založil divadelní společnost, která nakonec získala patronát krále Ludvíka XIV., což Molièrovi umožnilo uvádět svá díla na královském dvoře. Jeho hry, jako jsou Tartuffe, Lakomec a Misantrop, často kritizují společenské normy a lidské slabosti, využívají ostrý humor a satiru. Molière kombinoval prvky klasické italské commedia dell'arte a francouzské farce, aby vytvořil díla, která reflektují lidské chyby a předsudky, zároveň však nabízejí zábavu a morální ponaučení."
    },
    {
        dilo:"Hamlet, tragédie od Williama Shakespeara, je příběhem dánského prince, který se snaží pomstít smrt svého otce. Dílo začíná Hamletovým zjištěním, že jeho otec, král Dánska, byl zavražděn svým bratrem Claudiem, který poté usurpoval trůn a oženil se s Hamletovou matkou, královnou Gertrudou. Hamlet se potýká s morálními dilematy o pomstě a spravedlnosti, zatímco jeho duševní stav se postupně zhoršuje. Jeho znepokojivé chování a složité intriky vedou k řadě tragických událostí, včetně smrti Ofélie, Polonia, Rozencrantze, Guildensterna a nakonec i Hamleta samotného. Dílo zkoumá témata jako jsou zrada, pomsta, šílenství a morální rozklad.",
        autor:"William Shakespeare, narozený 23. dubna 1564 ve Stratfordu nad Avonou, je považován za jednoho z největších dramatiků. Jeho dílo zahrnuje 39 her a 154 sonetů, které zkoumají hluboké lidské emoce a etická dilemata. Mezi jeho nejznámější hry patří Hamlet, Othello, Král Lear a Macbeth. Tyto práce jsou ceněny pro jazykovou obratnost a psychologickou hloubku postav, reflektují společenské a politické napětí jeho doby a zároveň se dotýkají univerzálních témat jako láska, moc, zrada a pomsta. Shakespeare zemřel 23. dubna 1616, ale jeho vliv na světovou literaturu přetrvává."
    },
    {
        dilo:"Knihu Co Bůh? Člověk? napsal český spisovatel a filozof Bridel B. Toto dílo je filozofickou esejí, která se zamýšlí nad vztahem mezi božstvím a člověkem. Autor zkoumá, jak lidské pojetí božství ovlivňuje naše chápání samotného člověka, naše morální hodnoty a chování ve společnosti. Bridel B. klade otázky o povaze božství, lidské svobody a předurčení, zkoumá historický vývoj náboženských a filozofických myšlenek a jejich dopad na současné pochopení etiky a osobní identity. Esej je hlubokým zamyšlením nad těmito tématy, nabízející čtenářům prostor k reflexi o smyslu existence a lidského údělu.",
        autor:"Bedřich Bridel byl český jezuitský kněz, básník a misionář narozený v roce 1619 v Chrástu u Chrudimi a zemřel v roce 1680 ve Vídni. Je známý především svým literárním dílem, které se věnuje náboženským tématům, reflektuje jeho misijní zkušenosti a barokní duchovní literaturu. Bridelova poezie a próza jsou výrazem jeho hluboké víry a zkušeností z cest po Evropě a Svaté zemi. Jeho nejznámější díla zahrnují Co Bůh? Člověk?, kde prostřednictvím alegorií a biblických odkazů zprostředkovává etická a duchovní ponaučení. Bridel je považován za významného představitele české barokní literatury."
    },

];