export const dila = [
    {
        dilo:"Kulička je známé dílo francouzského spisovatele Guy de Maupassanta, které popisuje události z francouzsko-pruské války. Příběh sleduje osudy obyvatel francouzského městečka, kteří jsou nuceni se vyrovnat s pruskou okupací. Zvláštní pozornost je zaměřena na obchodníka Maître Cornudeta, jehož patriotické chování kontrastuje s pragmatickým přístupem ostatních obyvatel, kteří se snaží nalézt způsoby, jak se s okupačními silami vypořádat. Toto dílo, charakteristické Maupassantovou schopností vykreslit komplexní lidské emoce a sociální konflikty, reflektuje ironii a moralitu lidského chování v období konfliktu.",
        autor:"Guy de Maupassant byl francouzský spisovatel, známý pro svou mistrovskou tvorbu krátkých povídek, které často odkrývají temné a ironické stránky lidské povahy. Narodil se 5. srpna 1850 v Normandii a zemřel 6. července 1893 v Paříži. Jeho díla, ovlivněná realismem a naturalismem, se vyznačují jasným stylem, ekonomií slov a efektivním vyprávěním. Mezi jeho nejslavnější povídky patří Šperk, Kulička a Horla. Maupassant byl také autorem několika románů, včetně Bel-Ami, který kritizuje francouzskou společnost 19. století, a Pierre a Jean. Jeho práce často zkoumají psychologii postav v konfliktních situacích, a přestože trpěl duševní nemocí, která jeho život tragicky zkrátila, jeho literární odkaz zůstává významný."
    },
    {
        dilo:"Pes baskervillský od Arthura Conana Doylea je jedním z nejslavnějších případů Sherlocka Holmese. Příběh začíná, když Dr. Watson a Sherlock Holmes přijmou případ záhadné smrti Sira Charlese Baskervilla, obklopené pověstmi o prokletém rodinném dědictví a strašlivém psu strážícím rodové sídlo na venkově. Holmes a Watson se snaží chránit posledního dědice, Sira Henryho, před zdánlivě nadpřirozenou hrozbou. Během vyšetřování Holmes odhaluje lidské zlo a triky stojící za legendou. Kniha je plná napětí, detailního vyšetřování a nečekaných zvratů, a ukazuje Holmesovu analytickou genialitu ve vyvrcholení.",
        autor:"Arthur Conan Doyle byl britský spisovatel, nejvíce známý pro své příběhy o detektivu Sherlocku Holmesovi. Narodil se v roce 1859 ve Skotsku a zemřel v roce 1930. Původně lékařem, Doyle se proslavil literárně, když začal publikovat příběhy o Holmesovi a jeho věrném společníkovi Dr. Watsonovi. Tyto detektivní příběhy jsou ceněny pro jejich inovativní použití forenzních a logických technik vyšetřování. Kromě Holmese Doyle psal i historické romány, sci-fi a práce na téma spiritualismu, kterým se začal věnovat později ve svém životě. Jeho dílo mělo trvalý vliv na žánr detektivek a dobrodružné literatury."
    },
    {
        dilo:"Máj od K.H. Máchy je vrcholné dílo českého romantismu a jedno z nejvýznamnějších literárních děl české literatury. Báseň, napsaná ve formě veršovaného eposu, vypráví příběh mladého muže Viléma, který je odsouzen k smrti za vraždu. Text je bohatý na emotivní obrazy a přírodní motivy, které reflektují hluboké osobní i společenské tématy. Mácha v básni zkoumá otázky viny, osudu a nevyhnutelnosti smrti, přičemž se dotýká i témat lásky, zrady a odcizení. Báseň je známá svou lyrickou krásou a melodickým jazykem, který zůstává v české kultuře ikonický.",
        autor:"Karel Hynek Mácha byl český básník, prozaik a dramatik, považovaný za nejvýznamnějšího představitele českého romantismu. Narodil se 16. listopadu 1810 v Praze a zemřel předčasně 5. listopadu 1836 v Litoměřicích. Jeho nejslavnější dílo, báseň Máj, napsaná v roce 1836, revolučně ovlivnila českou literaturu svou formou, stylem a emotivní hloubkou. Mácha ve svém díle často zkoumá témata jako jsou osamělost, tragédie a touha po svobodě, což odráží jeho osobní zkušenosti i romantický ideál. Jeho díla a tragický osud silně rezonují v české národní identitě a literárním dědictví."
    },
    {
        dilo:"Král Lávra je satirická báseň českého básníka Karla Havlíčka Borovského, popisující příběh krále, který má tajemství: místo uší má oslí uši. Báseň se odehrává ve fiktivním království, kde král Lávra každý rok najímá nového holiče, aby mu stříhal vlasy a zjistil jeho tajemství. Holič se přísahou zaváže, že tajemství nikomu nevyzradí, ale nakonec své břemeno sdělí větru a stromu, což vede k rozšíření tajemství po celém království. Dílo je alegorií o mocenské korupci a hybných silách ve společnosti, které ovlivňují pravdu a spravedlnost.",
        autor:"Karel Havlíček Borovský byl český novinář, spisovatel, kritik a politik, narozený 31. října 1821 v Borové u Přibyslavi a zemřel 29. července 1856 v Králově Poli. Je považován za jednoho z prvních českých novinářů a jednu z nejvýraznějších postav českého národního obrození. Jeho práce výrazně ovlivnily směřování české literatury a politiky. Borovský byl známý svými ostrými satirami proti absolutismu a církevnímu dogmatismu, ačkoliv čelil politickému pronásledování a byl v roce 1851 deportován do Brixenu v Tyrolsku. Jeho nejznámějšími literárními díly jsou Král Lávra, Tyrolské elegie a Křest svatého Vladimíra."
    },

];