export const dila = [
    {
        dilo:"R.U.R. je divadelní hra napsaná českým spisovatelem Karlem Čapkem. Poprvé uvedena v roce 1920, pojednává o vzniku a pádu továrny na výrobu robotů, která se stane dominantním prvkem ve společnosti. Termín robot byl poprvé použit v této hře. Čapekova hra se dotýká otázek lidské identity, technologického pokroku a etiky vytváření umělé inteligence. R.U.R. je dnes považována za jedno z nejvýznamnějších děl sci-fi literatury a zanechala trvalý odkaz v literární historii.",
        autor:"Karel Čapek byl významným českým spisovatelem, dramatikem a novinářem. Narodil se v roce 1890 a zemřel v roce 1938. Jeho díla, jako jsou divadelní hry R.U.R. a Věc Makropulos, a romány jako Válka s mloky a Hordubal, ho učinila jedním z nejvýznamnějších literárních osobností své doby. Čapek je také známý svou kritikou totalitních režimů a za popularizaci termínu robot, který poprvé použil ve hře R.U.R. Jeho práce zanechala trvalý odkaz v literární historii a jeho myšlenky jsou stále aktuální."
    },
    {
        dilo:"Krysař, napsaný Viktorem Dykem, je temný a symbolický příběh o mladém kováři, který uzavírá pakt s ďáblem. Tímto pakt se mu dostane schopnost ovládat krysy. Povídka se odehrává v horské vesnici a líčí vzestup a pád kovářovy moci, zatímco obyvatelé vesnice se postupně potýkají se zlými důsledky jeho dohody s ďáblem. Krysař je často interpretován jako alegorie lidské touhy po moci a ztráty lidské morálky. Tato klasická česká povídka inspirovala mnoho adaptací v divadle, filmu a hudbě a má trvalý vliv na českou literaturu a kulturu.",
        autor:"Viktor Dyk byl český básník, prozaik, dramatik a politik, narodil se v roce 1877 a zemřel v roce 1931. Jeho dílo zahrnuje básnické sbírky, povídky, romány a divadelní hry. Mezi jeho nejznámější díla patří sbírka básní Krysař, která je považována za jeden z vrcholů české dekadence. Krysař je temný a symbolický příběh o mladém kováři, který uzavírá pakt s ďáblem a získává schopnost ovládat krysy. Tato povídka je považována za klasiku české literatury a inspiruje četné adaptace v divadle, filmu a hudbě. Dykovo dílo má trvalý vliv na českou literaturu a kulturu."
    },
    {
        dilo:"Maminka je básnická sbírka českého básníka Jaroslava Seiferta, která byla poprvé publikována v roce 1936. Sbírka reflektuje autorův vztah k matce, ale také k ženám obecně, a pojednává o ženské roli, mateřství a lásce. Seifert v básních věnuje pozornost nejen kráse a síle matčiny lásky, ale také oslavuje ženskost a její jedinečnost. Maminka je jednou z nejznámějších a nejoblíbenějších Seifertových sbírek a představuje jeho citlivý a lyrický přístup k tématu mateřství a rodiny.",
        autor:"aroslav Seifert byl český básník, narozený v roce 1901 a zemřel v roce 1986. Byl oceněn Nobelovou cenou za literaturu v roce 1984. Seifert byl významnou osobností české literatury 20. století a jeho dílo zahrnuje rozmanité básnické sbírky, eseje a prózu. Jeho tvorba je často spojována s lyrickým vyjádřením radosti z malých věcí a krásy života, ale také s kritikou totalitních režimů a obhajobou lidské důstojnosti. Seifertovo dílo zůstává důležitou součástí české literární krajiny a je ceněno jak doma, tak i v zahraničí."
    },
    {
        dilo:"Bílá nemoc je divadelní hra napsaná českým spisovatelem Karlem Čapkem v roce 1937. Tato hra je sci-fi tragédie, která se odehrává v dystopické budoucnosti. Příběh se točí kolem objevu léku na smrtelnou nemoc nazvanou bílá nemoc, který poskytuje imunitu pouze elitní třídě společnosti. To vede k rozporům mezi těmi, kteří mají lék, a těmi, kteří ne, a vzniku etických otázek týkajících se rovnosti a spravedlnosti. Čapkova hra je významným dílem české literatury a stále se diskutuje o jejích politických a filozofických tématech.",
        autor:"Karel Čapek byl významným českým spisovatelem, dramatikem, novinářem a překladatelem. Narodil se v roce 1890 a zemřel v roce 1938. Jeho dílo zahrnuje širokou škálu žánrů, včetně divadelních her, románů, povídek, eseji a cestopisů. Je známý pro svůj vynikající příspěvek k české literatuře a jeho práce ovlivnila mnoho dalších spisovatelů a umělců. Čapek je nejvíce známý pro popularizaci termínu robot, který poprvé použil ve své divadelní hře R.U.R. . Jeho díla jsou často zaměřena na sociální a politické téma a jsou známá svým ostrým intelektem a humorem."
    },
    {
        dilo:"Hordubal je román napsaný českým spisovatelem Karlem Čapkem a publikovaný v roce 1933. Příběh sleduje tragický osud Tomáše Hordubala, který je obviněn z vraždy a následně popraven. Vypráví o konfliktech mezi lidmi ve vesnickém prostředí a ukazuje jejich slabiny a lidské tragédie. Román je často chápán jako kritika mezilidských vztahů a společenských konvencí. Čapek se ve svém díle zaměřuje na psychologickou hloubku postav a jejich reakce na vnější tlaky a události. Hordubal patří k významným dílům české literatury 20. století a je stále často čten a studován.",
        autor:"Karel Čapek byl významným českým spisovatelem, dramatikem, novinářem a překladatelem. Narodil se v roce 1890 a zemřel v roce 1938. Jeho dílo zahrnuje širokou škálu žánrů, včetně divadelních her, románů, povídek, eseji a cestopisů. Je známý pro svůj vynikající příspěvek k české literatuře a jeho práce ovlivnila mnoho dalších spisovatelů a umělců. Čapek je nejvíce známý pro popularizaci termínu robot, který poprvé použil ve své divadelní hře R.U.R. . Jeho díla jsou často zaměřena na sociální a politické téma a jsou známá svým ostrým intelektem a humorem."
    },
    {
        dilo:"Bylo nás pět je román českého spisovatele Karla Poláčka, poprvé vydaný v roce 1936. Příběh sleduje osudy skupiny chlapců v Praze v průběhu první světové války. Hlavními postavami jsou Pepíno, Pipina, Tony, Sivý a Vacák. Román zobrazuje jejich dobrodružství, přátelství, ale také těžkosti a zkoušky, kterým čelí v době války. Bylo nás pět je považováno za jedno z nejznámějších děl české literatury pro mládež a je často zařazováno do školních četebních seznamů. Karel Poláček se ve svém díle zaměřuje na lidské hodnoty, přátelství a vztahy mezi lidmi.",
        autor:"Karel Poláček byl český spisovatel, narozený v roce 1892 a zemřel v roce 1945. Jeho dílo zahrnuje různé literární žánry, včetně prózy, dramatu a publicistiky. Mezi jeho nejznámější díla patří román Bylo nás pět, který je často považován za klasiku české literatury pro mládež. Poláček se ve svých dílech často zaměřoval na témata lidského soucitu, přátelství a solidarity, ale také na společenskou kritiku a humor. Jeho literární odkaz zůstává důležitým prvkem české literatury a je stále čten a studován."
    }
];