export const dila = [
    {
        dilo:"Let do nebezpečí je román od Arthura Haileyho, který popisuje dramatické události během komerčního letu. Příběh se zaměřuje na kapitána letadla, který musí řešit řadu náročných situací po tom, co je většina cestujících i posádky otrávena kontaminovaným jídlem. Kapitán, který se musí vypořádat nejen s vlastními zdravotními problémy ale i s technickými obtížemi letadla, je nucen spoléhat na pomoc nezkušeného kopilota a stewardky. Román nabízí napínavý pohled do světa letectví a zároveň zkoumá lidskou odvahu a rozhodnost v krizových situacích.",
        autor:"Arthur Hailey byl britsko-kanadský spisovatel, známý pro své detailně prozkoumané romány z různých průmyslových a obchodních prostředí. Narodil se 5. dubna 1920 ve Velké Británii a zemřel 24. listopadu 2004 na Bahamách. Předtím, než se stal úspěšným spisovatelem, sloužil v Royal Air Force během druhé světové války, což mu poskytlo zážitky, které později využil ve svých knihách. Jeho romány, jako Hotel, Let do nebezpečí, Kola a Airport, kombinují důkladný výzkum s napínavými zápletkami, čímž oslovují široké spektrum čtenářů. Hailey byl mistr v zobrazování složitých operačních systémů a lidských dramat v rámci nich."
    },
    {
        dilo:"Malý princ od Antoine de Saint-Exupéry je filozofická pohádka o cestě mladého prince z jiné planety. Tento příběh zkoumá témata lidské povahy a kritizuje moderní společnost skrze nevinné oči Malého prince, který navštěvuje různé planety, včetně Země, a setkává se s různými postavami symbolizujícími různé aspekty lidského života. Dílo odráží Saint-Exupéryho zkušenosti jako pilota a jeho pohledy na život, osamělost, přátelství a lásku. Kniha je ceněna pro svou hloubku a poetický jazyk, který oslovuje čtenáře všech věkových kategorií po celém světě.",
        autor:"Antoine de Saint-Exupéry byl francouzský spisovatel, pilot a průkopník letectví, narozený 29. června 1900 v Lyonu a nezvěstný od 31. července 1944 během letu nad Středozemním mořem. Jeho nejslavnější dílo, Malý princ, je považováno za literární klasiku a bylo přeloženo do mnoha jazyků. Kromě toho napsal řadu esejistických děl o létání a lidských hodnotách, včetně Nocní let a Válečný pilot. Tyto práce odhalují jeho filozofii a osobní zkušenosti, často zdůrazňují důležitost lidského ducha a potřebu smysluplných mezilidských vztahů."
    },
    {
        dilo:"Farma zvířat je román britského spisovatele George Orwella. Příběh líčí revoluci zvířat, které se spojí proti lidským pánům na farmě a získají kontrolu. Avšak postupem času nová vláda zvířat začne napodobovat chování lidských pánů a porušuje své vlastní ideály. Román jelegorickou kritikou totalitních režimů a manipulace s mocí. Orwellova práce je známá svými politickými názory a ostrou kritikou společnosti. Farma zvířat je důležitým dílem literatury 20. století, které se dotýká témat jako moc, korupce a manipulace.",
        autor:"George Orwell byl britský spisovatel, novinář a politický myslitel, vlastním jménem Eric Arthur Blair. Narodil se v roce 1903 a zemřel v roce 1950. Jeho nejznámějšími díly jsou romány 1984 a Farma zvířat. Orwell je známý svou kritikou totalitních režimů a manipulace s mocí. Během Španělské občanské války bojoval na straně republikánů, což ovlivnilo jeho politické názory. Jeho díla jsou často považována za zásadní kritiku totalitarismu, propagandy a manipulace s informacemi. Orwellovy myšlenky o dohledu státu a omezování svobody se staly klíčovými pojmy v diskusi o politické svobodě."
    },
    {
        dilo:"451 stupňů Fahrenheita je dystopický román napsaný americkým spisovatelem Rayem Bradburym v roce 1953. Příběh se odehrává ve společnosti, kde jsou knihy zakázány a veškeré myšlenky jsou kontrolovány vládou. Hlavní postavou je Guy Montag, hasič, který je pověřen pálením knih, což je standardní praxe ve společnosti, která chce potlačit nezávislé myšlení a kreativitu. Montag začne pochybovat o svém úkolu a snaží se porozumět významu knih a svobody myšlení. Román je významným dílem science fiction a je často považován za kritiku cenzury a útlaku.",
        autor:"ay Bradbury, americký spisovatel, proslul svými sci-fi, fantasy a hororovými díly. Mezi nejvýznamnější patří 451 stupňů Fahrenheita, Martinské kroniky a Temná polnice. Jeho literatura často sonduje témata cenzury, manipulace s informacemi a lidské touhy. Bradburyho styl je poetický a filozofický, jeho díla často reflektují současnou společnost. Narodil se v roce 1920 v Illinois, zemřel v 2012 v Los Angeles. Dětství strávil čtením a psaním, což formovalo jeho uměleckou vizi. Jeho literární odkaz zůstává silný, inspirovává generace čtenářů i spisovatelů po celém světě."
    },
    {
        dilo:"Stařec a moře je román napsaný americkým spisovatelem Ernestem Hemingwayem v roce 1952. Příběh sleduje starého rybáře jménem Santiago, který se vydává na moře na epický lov mečouna. Poté, co chytí obrovskou rybu, bojuje s ní po několik dní, než ji konečně porazí. Avšak na cestě zpět do přístavu je jeho úlovek zničen žraloky. Přesto Santiago neztrácí sílu ani odhodlání a nakonec se vrací domů s vnitřním klidem a hrdostí. Román zkoumá témata lidské vytrvalosti, síly a vyrovnávání se s osudem.",
        autor:"Ernest Hemingway, americký spisovatel, se narodil v roce 1899 a zemřel v roce 1961. Jeho strohý a minimalistický styl psaní ho proslavil jako jednoho z nejvýznamnějších spisovatelů 20. století. Mezi jeho nejznámější díla patří Sbohem, armádo a Komu zvoní hrana. V roce 1954 obdržel Nobelovu cenu za literaturu. Jeho životní styl a dobrodružný duch ovlivnily mnoho dalších spisovatelů a umělců. Hemingwayova práce zanechala trvalý odkaz na literární scéně a jeho díla jsou stále oblíbená po celém světě."
    },

];